# Generated by Django 5.1 on 2024-08-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=40)),
                ('post_index', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('pasport_number', models.CharField(max_length=4)),
                ('pasport_seria', models.CharField(max_length=6)),
                ('issued_by', models.CharField(max_length=100)),
                ('department_code', models.CharField(max_length=7)),
                ('inn_number', models.CharField(max_length=12)),
                ('snils_number', models.CharField(max_length=20)),
            ],
        ),
    ]
