# Generated by Django 5.1 on 2024-08-28 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2022, 5, 13, 0, 0)),
            preserve_default=False,
        ),
    ]
