# Generated by Django 5.1.1 on 2024-10-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
