# Generated by Django 5.1 on 2024-08-30 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0003_alter_person_pasport_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=30, verbose_name='город проживания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_issue',
            field=models.DateField(verbose_name='Жата выдачи'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department_code',
            field=models.CharField(max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn_number',
            field=models.CharField(max_length=12, verbose_name='Номер ИНН'),
        ),
        migrations.AlterField(
            model_name='person',
            name='issued_by',
            field=models.CharField(max_length=100, verbose_name='Место выдачи'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pasport_number',
            field=models.CharField(max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pasport_seria',
            field=models.CharField(max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(max_length=30, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_index',
            field=models.CharField(max_length=8, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='person',
            name='snils_number',
            field=models.CharField(max_length=20, verbose_name='Номер СНИЛС'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(max_length=40, verbose_name='Улиа'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=24, verbose_name='Номер счета')),
                ('corr_account', models.CharField(max_length=24, verbose_name='Корр. счет')),
                ('bank_name', models.CharField(max_length=50, verbose_name='Банк получателя')),
                ('bic', models.CharField(max_length=9, verbose_name='БИК')),
                ('inn', models.CharField(max_length=15, verbose_name='ИНН банка')),
                ('kpp', models.CharField(max_length=15, verbose_name='КПП банка')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='client_crud.person')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
            },
        ),
    ]
