# Generated by Django 5.1 on 2024-08-30 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0004_alter_person_options_alter_person_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='tags_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='client_crud.tags', verbose_name='Теги'),
        ),
    ]
