# Generated by Django 5.1 on 2024-09-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0006_rename_tags_tag_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_of_issue',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(max_length=40, verbose_name='Улица'),
        ),
    ]
