# Generated by Django 5.1.1 on 2024-09-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0007_alter_person_date_of_issue_alter_person_street'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pasport_number',
            new_name='passport_number',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='pasport_seria',
            new_name='passport_seria',
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер ИНН'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('A', 'Автоперекуп'), ('N', 'Недвижимость'), ('S', 'Спецтехника'), ('F', 'Сельхозтехника')], db_index=True, max_length=20, verbose_name='Теги'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=30, verbose_name='Область')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('district', models.CharField(max_length=30, verbose_name='Район')),
                ('street', models.CharField(max_length=30, verbose_name='Улица')),
                ('home_number', models.CharField(max_length=30, verbose_name='Номер дома')),
                ('apartment_number', models.CharField(max_length=30, verbose_name='Номер квартиры')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='client_crud.person')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['city'],
            },
        ),
    ]
