# Generated by Django 5.1.1 on 2024-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0009_alter_address_apartment_number_alter_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(max_length=100, verbose_name='Место рождения'),
        ),
    ]
