# Generated by Django 5.1.1 on 2024-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0010_alter_person_place_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(help_text='Введите Город проживания', max_length=50, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(help_text='Введите Дату раждения', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_issue',
            field=models.DateField(help_text='Введите дату выдочи паспорта', verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department_code',
            field=models.CharField(help_text='Введите код подразделения паспорта', max_length=7, verbose_name='Код подразделения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(help_text='Введите Электронную почту', max_length=100, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='inn_number',
            field=models.CharField(help_text='Введите Номер ИНН', max_length=12, unique=True, verbose_name='Номер ИНН'),
        ),
        migrations.AlterField(
            model_name='person',
            name='issued_by',
            field=models.CharField(help_text='Введите Место выдачи паспорта', max_length=100, verbose_name='Место выдачи'),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(help_text='Введите Фамилию', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Введите Имя', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport_number',
            field=models.CharField(help_text='Введите Номер паспорта', max_length=6, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport_seria',
            field=models.CharField(help_text='Введите Серию паспорта', max_length=4, verbose_name='Серия паспорта'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(help_text='Введите Номер телефона', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(help_text='Введите Место рождения', max_length=100, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_index',
            field=models.CharField(help_text='Введите Почтовый индекс', max_length=10, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='person',
            name='snils_number',
            field=models.CharField(help_text='Введите Номер СНИЛС', max_length=20, verbose_name='Номер СНИЛС'),
        ),
        migrations.AlterField(
            model_name='person',
            name='street',
            field=models.CharField(help_text='Введите Улицу Согласно прописки клиента', max_length=50, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(help_text='Введите Отчество', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
